# Generated by Django 2.2 on 2020-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
