# Generated by Django 2.2 on 2020-06-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='1234', max_length=200),
        ),
    ]
