# Generated by Django 2.2 on 2020-06-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200604_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
