# Generated by Django 2.2 on 2020-06-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
