# Generated by Django 2.2 on 2020-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200610_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='answer',
            field=models.CharField(default='Query is not yet answered', max_length=400),
        ),
        migrations.AlterField(
            model_name='query',
            name='subject',
            field=models.CharField(default='Query', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
