# Generated by Django 2.2 on 2020-06-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200610_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='status',
            new_name='queryStatus',
        ),
    ]
